name: Publish Tiveria.Home.Knx Package

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
       
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.11
      with:
          versionSpec: '5.8.x'
 
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Determine Version
      id: gitversion
      uses: gittools/actions/gitversion/execute@v0.9.7
      with:
        useConfigFile: true
        
    - name: Display SemVer
      run: | 
        echo "SemVer: $GITVERSION_SEMVER"

    - name: Test
      run: dotnet test -c Release --verbosity normal

    - name: Build
      run: dotnet build --no-restore /p:Version=${{ steps.gitversion.outputs.AssemblySemVer }} /p:AssemblyVersion=${{ steps.gitversion.outputs.AssemblySemVer }} /p:InformationalVersion=${{ steps.gitversion.outputs.InformationalVersion }}

    - name: Publish Tiveria.Home.Knx
      run: dotnet nuget push *.nupkg -k ${{secrets.NUGET_API_KEY}} -s https://api.nuget.org/v3/index.json
#      uses: brandedoutcast/publish-nuget@v2.5.2
#      with:
#          PROJECT_FILE_PATH: src/Tiveria.Home.Knx/Tiveria.Home.Knx.csproj
#          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
