name: Publish Tiveria.Home.Knx Package

on:
  push:
    branches: [ V2 ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build -c Release
    - name: Test
      run: dotnet test -c Release --no-build --verbosity normal
    - name: Publish Tiveria.Home.Knx
      uses: brandedoutcast/publish-nuget@v2.5.2
      with:
          PROJECT_FILE_PATH: src/Tiveria.Home.Knx/Tiveria.Home.Knx.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
